Fix overwriteing held item when copying block
PixelGuys/Cubyz pull request #662
Opened 2024-09-02 07:49 UTC by ttmso

When you middle click a block and your selected slot has an item. Instead of overwriteing it the block will get added to the first empty slot in the hotbar, and if you have no open slots in your hotbar it will just overwrite the selected slot.

2024-09-03 18:34 UTC, IntegratedQuantum reviewed
I just tried this and I think there is one more thing missing:
When an item is already present in the hotbar, switch to that slot and fill it up.
Would you mind adding this real quick? Otherwise I can also merge this and make a separate issue for it.

2024-09-03 18:34 UTC, IntegratedQuantum commented on src/game.zig
> +					return;
Also, please change this to a break, a return might have unintended consequences in the future.

2024-09-03 18:53 UTC, ttmso commented
Tomorrow, I have to go sleep.

2024-09-04 08:13 UTC, ttmso commented
Done!

2024-09-04 18:03 UTC, IntegratedQuantum requested changes
It looks like you made a small mistake while implementing the new behavior:
It seems to always put a new item into the first empty slot, instead of a selected empty slot.

2024-09-04 18:06 UTC, ttmso commented
Oh okay, I'm going to fix that.

2024-09-04 18:36 UTC, IntegratedQuantum commented
Looks good, thanks for adding in my extension.
It really feels a lot better now.
We might need some further improvements once #670 is a thing, to ensure conservation of matter, but that's a different thing.

2024-09-04 18:36 UTC, merged