Make planks tool materials
PixelGuys/Cubyz pull request #772
Opened 2024-11-10 20:47 UTC by careeoki

You can use planks to craft tools, and they each have unique stats (which will probably have to be rebalanced later)
![image](https://github.com/user-attachments/assets/d8fe89dc-a2b6-4c84-8b4d-5329874af8c8)
Oak has the values from sticks, and is the "standard" wood type.
- Birch is faster, but with less durability
- Pine is slower, but with more durability
- Mahogany is more powerful, but would be a more dangerous biome than others (hypothetically, in the future :P)

Also updated the cobble material palette to match the newest texture.

2024-11-10 21:04 UTC, IntegratedQuantum requested changes
This is nice, thank you!
And yeah, don't worry too much about the values. They will need to be balanced in the future anyways.

There are a few formatting problems though.

2024-11-10 21:04 UTC, IntegratedQuantum commented on assets/cubyz/blocks/birch_planks.zig.zon
> +	}
Please correctly indent this and put a comma at the end:
```zig
	.item = .{
		.material = .{
			.density = 0.6,
			.resistance = 0.8,
			.power = 0.2,
			.roughness = 0.7,
			.colors = .{
				0xff9b7a5b, 0xffbf9872, 0xffdeb287, 0xfff2c89c, 0xffffdfb7,
			},
		},
	},
```

2024-11-10 21:04 UTC, IntegratedQuantum commented on assets/cubyz/blocks/birch_planks.zig.zon
> +}
unintended change

2024-11-10 21:04 UTC, IntegratedQuantum commented on assets/cubyz/blocks/mahogany_planks.zig.zon
> +	}
same as above

2024-11-10 21:04 UTC, IntegratedQuantum commented on assets/cubyz/blocks/oak_planks.zig.zon
> +	}
same as above

2024-11-10 21:04 UTC, IntegratedQuantum commented on assets/cubyz/blocks/pine_planks.zig.zon
> +	}
same as above

2024-11-11 00:39 UTC, careeoki commented
Okay, I fixed those issues. Let me know if it's good.

2024-11-11 15:13 UTC, IntegratedQuantum approved these changes
Much better, thank you.

2024-11-11 15:13 UTC, merged