fix: dont show kick for local user
PixelGuys/Cubyz pull request #822
Opened 2024-12-09 11:25 UTC by somanshurath

2024-12-09 11:33 UTC, somanshurath commented
Preview:
![Screenshot from 2024-12-09 16-50-17](https://github.com/user-attachments/assets/2e2f0cb6-706f-418b-bf85-0392d9aec61a)

2024-12-09 15:48 UTC, IntegratedQuantum commented on src/network.zig
> +	pub const kick = struct {
I would prefer to have this as part of the disconnect protocol, you could for example just transfer a one-byte enum with the disconnect reason.

2024-12-09 15:49 UTC, IntegratedQuantum commented on src/network.zig
> +		pub const id: u8 = 21;
Please don't just use random numbers as protocol ids.

2024-12-09 17:59 UTC, somanshurath commented
@IntegratedQuantum as of now we have three possible "disconnect" reasons right?
- kicked
- exit
- connectionError

2024-12-10 07:27 UTC, IntegratedQuantum commented
Yes. We could have more in the future though.

2024-12-15 11:18 UTC, IntegratedQuantum requested changes

2024-12-15 11:18 UTC, IntegratedQuantum commented on src/main.zig
> +	exitNotification.store(exitData, .monotonic);
Having two atomics like this is a problem.
The main thread could see the new value of `shouldExitToMenu`, but still see the old value of `exitNotification`, which causes a small chances of seeing an incorrect exit value.

Could you maybe just use one attomic of `?network.DisconnectType` to cover both in one?

2024-12-15 11:18 UTC, IntegratedQuantum commented on src/network.zig
> +pub const DisconnectType = enum(u8) {
I don't particularly like that this is just declared randomly at the beginning of the file.
Wouldn't it make more sense to move it into the `disconnect` protocol?

2024-12-15 11:18 UTC, IntegratedQuantum commented on src/network.zig
> +		}
Incorrect indentation

2025-02-21 16:50 UTC, IntegratedQuantum commented
Do you still intend to work on this? It's been a few months since your last change.

2025-06-04 20:15 UTC, IntegratedQuantum commented
Closing due to inactivity. If/when you intend to work on this again please fix the merge conflicts and reopen.

2025-06-04 20:15 UTC, closed without merging